# Default requirements
[T5.all.default.all.cola_a]

input = "cola sentence: All your base are belong to us."
label = "unacceptable"

# t5-small is gets some results differently
[T5.all.t5-small.all.cola_a]

label = "acceptable"

[T5.all."google/flan-t5-small".all.cola_a]

label = "cola"

[T5.all."google/flan-t5-base".all.cola_a]

label = "cola"

[T5.all."google/flan-t5-large".all.cola_a]

label = "cola"

[T5.all."google/flan-t5-xl".all.cola_a]

label = "All your base are belong to us."

[T5.all."google/flan-t5-xxl".all.cola_a]

label = "cola"

[T5.all.default.all.premise_a]

input = "premise: I hate pigeons. hypothesis: My feelings towards pigeons are filled with animosity."
label = "entailment"

# t5-small is gets some results differently
[T5.all.t5-small.all.premise_a]

label = "contradiction"

[T5.all."google/flan-t5-small".all.premise_a]

label = "it is not possible to tell"

[T5.all."google/flan-t5-base".all.premise_a]

label = "it is not possible to tell"

[T5.all."google/flan-t5-large".all.premise_a]

label = "yes"

[T5.all."google/flan-t5-xl".all.premise_a]

label = "yes"

[T5.all."google/flan-t5-xxl".all.premise_a]

label = "yes"

[T5.all.default.all.translate_a]

input = "translate English to German: That is good."
label = "Das ist gut."

# t5-base also gets results differently
[T5.all.t5-base.all.translate_a]

label = "Das ist gut so."

[T5.all.default.all.premise_b]

input = "premise: If I fall asleep then I am going to wake up in 8 hours. hypothesis: I fell asleep but did not wake up in 8 hours."
label = "contradiction"

[T5.all."google/flan-t5-small".all.premise_b]

label = "no"

[T5.all."google/flan-t5-base".all.premise_b]

label = "yes"

[T5.all."google/flan-t5-large".all.premise_b]

label = "no"

[T5.all."google/flan-t5-xl".all.premise_b]

label = "no"

[T5.all."google/flan-t5-xxl".all.premise_b]

label = "no"
