version = "1.0.0"
 
[oss]
 
# If you are not adding excluded directories then remove [oss.excluded] and [[oss.excluded.directories]] both tag from file.
[oss.excluded]
 
[[oss.excluded.directories]]
paths = ['third_party/protobuf/csharp/src'] 
comment = 'C# source not used in OSS build. See https://jirasw.nvidia.com/browse/PSIRT-1067 for approval'
